/*
Deployment script for master

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "master"
:setvar DefaultFilePrefix "master"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 58052ab5-7c11-407e-bb3e-7de711e41fad is skipped, element [dbo].[MultilingualString].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 67c7f9bb-b5d4-4b2f-bee9-8d5a5cc432ec is skipped, element [dbo].[MLSValues].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 3d3db7e3-e097-4d1e-941d-b3f0fcb88a2e is skipped, element [dbo].[OrgName].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key a594cac8-1fa1-4674-9457-0576692dc713 is skipped, element [dbo].[Organization].[SupervisoryOrganization] (SqlSimpleColumn) will not be renamed to SupervisoryOrganizationID';


GO
PRINT N'Rename refactoring operation with key d10be975-513c-4329-a603-a0f99b8bc63f is skipped, element [dbo].[Organization].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key de0d6c88-09cb-405a-b72b-a166dfb77ee9 is skipped, element [dbo].[Person].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 91512ec2-4636-4670-8645-8c617302b1c5 is skipped, element [dbo].[PersonName].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 43b44248-25da-4941-adc3-1262624a7838 is skipped, element [dbo].[PersonName].[PrefixID] (SqlSimpleColumn) will not be renamed to PrefixMLSID';


GO
PRINT N'Rename refactoring operation with key c59e8f40-4c68-492e-b6fa-179346efee17 is skipped, element [dbo].[Teacher].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 19487e5b-1320-438d-bfea-e082abf063b7 is skipped, element [dbo].[Student].[Id] (SqlSimpleColumn) will not be renamed to ID';


GO
PRINT N'Rename refactoring operation with key 8656c0f3-b7d3-4a59-835a-63fb56333ec5 is skipped, element [dbo].[Teacher].[EffectiveFrom] (SqlSimpleColumn) will not be renamed to Date';


GO
PRINT N'Rename refactoring operation with key 1cb7f502-6c7e-4320-947e-b971d60c0e7b is skipped, element [dbo].[Teacher].[EffectiveTo] (SqlSimpleColumn) will not be renamed to ReceiptNo';


GO
PRINT N'Rename refactoring operation with key 5e482b0f-192d-41fb-beca-7e7ef613091b is skipped, element [dbo].[Receipt].[A] (SqlSimpleColumn) will not be renamed to AmountPerUnit';


GO
PRINT N'Rename refactoring operation with key f4e2e437-f021-4327-a5df-0cc523403af9, 44c22e2e-791e-4091-8b78-e624c28cfd7f is skipped, element [dbo].[ReceivableItem].[T] (SqlSimpleColumn) will not be renamed to EffectiveTo';


GO
PRINT N'Rename refactoring operation with key 6c92e556-8130-4ce0-b9db-96a6ec385eb3 is skipped, element [dbo].[ReceivableItem].[From] (SqlSimpleColumn) will not be renamed to EffectiveFrom';


GO
PRINT N'Creating [dbo].[A]...';


GO
CREATE TABLE [dbo].[A] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [Code]            NVARCHAR (30)  NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [ClassLevelID]    BIGINT         NULL,
    [SchoolID]        INT            NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Absence]...';


GO
CREATE TABLE [dbo].[Absence] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [AbsenceHours]   NVARCHAR (30)  NULL,
    [CategoryID]     INT            NULL,
    [Date]           DATETIME2 (7)  NULL,
    [Reference]      NVARCHAR (200) NULL,
    [Remark]         NVARCHAR (400) NULL,
    [StudentID]      INT            NULL,
    [ClassSectionID] INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AcademicAchievement]...';


GO
CREATE TABLE [dbo].[AcademicAchievement] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [Code]                   NVARCHAR (30)  NULL,
    [Date]                   DATETIME2 (7)  NULL,
    [Description]            NVARCHAR (400) NULL,
    [Reference]              NVARCHAR (200) NULL,
    [Remark]                 NVARCHAR (400) NULL,
    [PersonID]               INT            NULL,
    [PerformanceIndicatorID] INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AcademicEventParticipation]...';


GO
CREATE TABLE [dbo].[AcademicEventParticipation] (
    [ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [Code]                    NVARCHAR (30)  NULL,
    [StartDate]               DATETIME2 (7)  NULL,
    [EndDate]                 DATETIME2 (7)  NULL,
    [Reference]               NVARCHAR (200) NULL,
    [Remark]                  NVARCHAR (400) NULL,
    [PersonID]                INT            NULL,
    [AcademicEventCategoryID] INT            NULL,
    [AcademicEventTitle]      NVARCHAR (400) NULL,
    [Description]             NVARCHAR (400) NULL,
    [Venue]                   NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Admission]...';


GO
CREATE TABLE [dbo].[Admission] (
    [ID]                            INT            IDENTITY (1, 1) NOT NULL,
    [AdmissionID]                   INT            NULL,
    [SeqNo]                         INT            NULL,
    [AdmittedClassLevelID]          INT            NULL,
    [ApplicationReceiptTemplateID]  BIGINT         NULL,
    [ApplicationFormURL]            NVARCHAR (200) NULL,
    [ApplicationInfoURL]            NVARCHAR (200) NULL,
    [ApplyFrom]                     DATETIME2 (7)  NULL,
    [ApplyTo]                       DATETIME2 (7)  NULL,
    [RegistrationFormURL]           NVARCHAR (200) NULL,
    [RegistrationReceiptTemplateID] BIGINT         NULL,
    [RegistrationInfoURL]           NVARCHAR (100) NULL,
    [RegisterFrom]                  DATETIME2 (7)  NULL,
    [RegisterTo]                    DATETIME2 (7)  NULL,
    [OrientationDate]               DATETIME2 (7)  NULL,
    [TestResultPublishDate]         DATETIME2 (7)  NULL,
    [SemesterID]                    INT            NULL,
    [SchoolID]                      INT            NULL,
    [DescriptionMLSID]              BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AdmissionTest]...';


GO
CREATE TABLE [dbo].[AdmissionTest] (
    [ID]               INT           IDENTITY (1, 1) NOT NULL,
    [AdmissionID]      INT           NULL,
    [SeqNo]            INT           NULL,
    [TestFrom]         DATETIME2 (7) NULL,
    [TestTo]           DATETIME2 (7) NULL,
    [DescriptionMLSID] BIGINT        NULL,
    [TitleMLSID]       BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AdmissionTestRoom]...';


GO
CREATE TABLE [dbo].[AdmissionTestRoom] (
    [ID]                  INT NOT NULL,
    [AdmissionID]         INT NULL,
    [AdmissionTestRoomID] INT NULL,
    [Capacity]            INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AdmitCurriculum]...';


GO
CREATE TABLE [dbo].[AdmitCurriculum] (
    [ID]               INT    IDENTITY (1, 1) NOT NULL,
    [AdmissionID]      INT    NULL,
    [Capacity]         INT    NULL,
    [CurriculumID]     INT    NULL,
    [DescriptionMLSID] BIGINT NULL,
    [TitleMLSID]       BIGINT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[AlternateSchool]...';


GO
CREATE TABLE [dbo].[AlternateSchool] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [Rank]                 INT            NULL,
    [Reference]            NVARCHAR (200) NULL,
    [Remark]               NVARCHAR (400) NULL,
    [StudentApplicationID] INT            NULL,
    [SchoolID]             INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Application]...';


GO
CREATE TABLE [dbo].[Application] (
    [ID]              INT            NOT NULL,
    [Code]            NVARCHAR (30)  NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [TitleMLSID]      BIGINT         NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassLevel]...';


GO
CREATE TABLE [dbo].[ClassLevel] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [CategoryID]      INT            NULL,
    [Code]            NVARCHAR (30)  NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [LevelNo]         INT            NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassLevelSection]...';


GO
CREATE TABLE [dbo].[ClassLevelSection] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [ClassLevelID]    INT            NULL,
    [SchoolID]        INT            NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Classroom]...';


GO
CREATE TABLE [dbo].[Classroom] (
    [ID]                  INT    IDENTITY (1, 1) NOT NULL,
    [ClassLevelSectionID] INT    NULL,
    [SchoolID]            INT    NULL,
    [RoomID]              BIGINT NULL,
    [SemesterID]          BIGINT NULL,
    [SemesterNo]          INT    NULL,
    [AcademicYear]        INT    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassroomStudent]...';


GO
CREATE TABLE [dbo].[ClassroomStudent] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [ClassLevelID]    INT            NULL,
    [ClassroomID]     INT            NULL,
    [GPA]             FLOAT (53)     NULL,
    [SchoolID]        INT            NULL,
    [StudentID]       INT            NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassroomTeacher]...';


GO
CREATE TABLE [dbo].[ClassroomTeacher] (
    [ID]              BIGINT         IDENTITY (1, 1) NOT NULL,
    [CategoryID]      INT            NULL,
    [ClassroomID]     INT            NULL,
    [TeacherID]       INT            NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [ClassLevelID]    BIGINT         NULL,
    [SchoolID]        INT            NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassSection]...';


GO
CREATE TABLE [dbo].[ClassSection] (
    [ID]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [ClassLevelSectionID] BIGINT         NULL,
    [CourseID]            BIGINT         NULL,
    [RoomID]              BIGINT         NULL,
    [SchoolID]            INT            NULL,
    [SemesterID]          BIGINT         NULL,
    [EffectiveFrom]       DATETIME2 (7)  NULL,
    [EffectiveTo]         DATETIME2 (7)  NULL,
    [Remark]              NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassSectionStudent]...';


GO
CREATE TABLE [dbo].[ClassSectionStudent] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [ClassSectionID] BIGINT         NULL,
    [StudentID]      BIGINT         NULL,
    [GradeID]        INT            NULL,
    [GradePoint]     REAL           NULL,
    [AttendedHours]  REAL           NULL,
    [EffectiveFrom]  DATETIME2 (7)  NULL,
    [EffectiveTo]    DATETIME2 (7)  NULL,
    [Reference]      NVARCHAR (200) NULL,
    [Remark]         NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ClassSectionTeacher]...';


GO
CREATE TABLE [dbo].[ClassSectionTeacher] (
    [ID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [ClassSectionID] BIGINT         NULL,
    [TeacherID]      BIGINT         NULL,
    [EffectiveFrom]  DATETIME2 (7)  NULL,
    [EffectiveTo]    DATETIME2 (7)  NULL,
    [Reference]      NVARCHAR (200) NULL,
    [Remark]         NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Configuration]...';


GO
CREATE TABLE [dbo].[Configuration] (
    [ID]                                     INT           IDENTITY (1, 1) NOT NULL,
    [SystemID]                               INT           NOT NULL,
    [EffectiveFrom]                          DATETIME2 (7) NOT NULL,
    [EffectiveTo]                            DATETIME2 (7) NULL,
    [AcademicLevelRootID]                    INT           NULL,
    [BloodGroupRootID]                       INT           NULL,
    [CourseCategoryRootID]                   INT           NULL,
    [GenderRootID]                           INT           NULL,
    [MajorRootID]                            INT           NULL,
    [OccupationRootID]                       INT           NULL,
    [RaceRootID]                             INT           NULL,
    [RelativeCategoryID]                     INT           NULL,
    [ReligionRootID]                         INT           NULL,
    [StudentStatusRootID]                    INT           NULL,
    [SchoolPositionRootID]                   INT           NULL,
    [SchoolSupervisorCategoryRootID]         INT           NULL,
    [DefaultCountryCode]                     NCHAR (3)     NULL,
    [DefaultDateCultureName]                 NVARCHAR (30) NULL,
    [DefaultDateFormat]                      NVARCHAR (50) NULL,
    [DefaultLanguageCode]                    NCHAR (5)     NULL,
    [CurriculumCourseCategoryRootID]         INT           NULL,
    [RoyalDecorationRootID]                  INT           NULL,
    [GuardianCategoryID]                     INT           NULL,
    [FatherCategoryID]                       INT           NULL,
    [MotherCategoryID]                       INT           NULL,
    [PersonPersonRelationshipCategoryRootID] INT           NULL,
    [EducationLevelRootID]                   INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Country]...';


GO
CREATE TABLE [dbo].[Country] (
    [Alpha3Code] NCHAR (3) NOT NULL,
    [Code]       NCHAR (3) NULL,
    [Alpha2Code] NCHAR (2) NULL,
    [TitleMLSID] BIGINT    NULL,
    PRIMARY KEY CLUSTERED ([Alpha3Code] ASC)
);


GO
PRINT N'Creating [dbo].[Country].[Country_UIX_Alpha2]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [Country_UIX_Alpha2]
    ON [dbo].[Country]([Alpha2Code] ASC)
    ON [PRIMARY];


GO
PRINT N'Creating [dbo].[Course]...';


GO
CREATE TABLE [dbo].[Course] (
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [Code]              NVARCHAR (30)  NULL,
    [CourseNoMLSID]     BIGINT         NULL,
    [DescriptionMLSID]  BIGINT         NULL,
    [ShortTitleMLSID]   BIGINT         NULL,
    [TitleMLSID]        BIGINT         NULL,
    [CreditHours]       REAL           NULL,
    [ClassLevelID]      BIGINT         NULL,
    [OutcomeCategoryID] INT            NULL,
    [SchoolID]          INT            NULL,
    [GradingSystemID]   INT            NULL,
    [EffectiveFrom]     DATETIME2 (7)  NULL,
    [EffectiveTo]       DATETIME2 (7)  NULL,
    [Reference]         NVARCHAR (200) NULL,
    [Remark]            NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Curriculum]...';


GO
CREATE TABLE [dbo].[Curriculum] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom]         DATETIME2 (7)  NULL,
    [EffectiveTo]           DATETIME2 (7)  NULL,
    [CurriculumFrameworkID] INT            NULL,
    [ShortTitleMLSID]       BIGINT         NULL,
    [TitleMLSID]            BIGINT         NULL,
    [Reference]             NVARCHAR (200) NULL,
    [Remark]                NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[CurriculumCourse]...';


GO
CREATE TABLE [dbo].[CurriculumCourse] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom] DATETIME2 (7)  NULL,
    [EffectiveTo]   DATETIME2 (7)  NULL,
    [CategoryID]    INT            NULL,
    [CurriculumID]  INT            NULL,
    [CourseID]      INT            NULL,
    [Reference]     NVARCHAR (200) NULL,
    [Remark]        NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[CurriculumFramework]...';


GO
CREATE TABLE [dbo].[CurriculumFramework] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [Code]            NVARCHAR (40) NULL,
    [EffectiveFrom]   DATETIME2 (7) NULL,
    [EffectiveTo]     DATETIME2 (7) NULL,
    [ShortTitleMLSID] BIGINT        NULL,
    [TitleMLSID]      BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[DesiredOutcome]...';


GO
CREATE TABLE [dbo].[DesiredOutcome] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [Discriminator]          TINYINT        NULL,
    [Code]                   NVARCHAR (30)  NULL,
    [CurriculumFrameworkID]  INT            NULL,
    [DefaultGradingSystemID] INT            NULL,
    [ParentID]               INT            NULL,
    [EffectiveFrom]          DATETIME2 (7)  NULL,
    [EffectiveTo]            DATETIME2 (7)  NULL,
    [Reference]              NVARCHAR (200) NULL,
    [Remark]                 NVARCHAR (400) NULL,
    [ClassLevelID]           BIGINT         NULL,
    [ShortTitleMLSID]        BIGINT         NULL,
    [TitleMLSID]             BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[DiscreteGrade]...';


GO
CREATE TABLE [dbo].[DiscreteGrade] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [Symbol]          NVARCHAR (8)   NULL,
    [Point]           REAL           NULL,
    [Description]     NVARCHAR (400) NULL,
    [GradingSystemID] BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Education]...';


GO
CREATE TABLE [dbo].[Education] (
    [ID]                       INT            IDENTITY (1, 1) NOT NULL,
    [PersonID]                 INT            NULL,
    [EffectiveFrom]            DATETIME2 (7)  NULL,
    [EffectiveTo]              DATETIME2 (7)  NULL,
    [Reference]                NVARCHAR (200) NULL,
    [Remark]                   NVARCHAR (400) NULL,
    [ShortTitleMLSID]          BIGINT         NULL,
    [TitleMLSID]               BIGINT         NULL,
    [StartDate]                INT            NULL,
    [GraduatedDate]            INT            NULL,
    [EducationLevelID]         INT            NULL,
    [AcademicInstituteName]    INT            NULL,
    [AcademicInstituteAddress] INT            NULL,
    [DegreeTitle]              INT            NULL,
    [ShortDegreeTitle]         INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Experience]...';


GO
CREATE TABLE [dbo].[Experience] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [PersonID]            INT            NULL,
    [EffectiveFrom]       DATETIME2 (7)  NULL,
    [EffectiveTo]         DATETIME2 (7)  NULL,
    [Reference]           NVARCHAR (200) NULL,
    [Remark]              NVARCHAR (400) NULL,
    [OrganizationID]      INT            NULL,
    [OrganizationName]    NVARCHAR (200) NULL,
    [OrganizationAddress] NVARCHAR (200) NULL,
    [JobDescription]      NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[GeographicAddress]...';


GO
CREATE TABLE [dbo].[GeographicAddress] (
    [ID]             BIGINT        IDENTITY (1, 1) NOT NULL,
    [AddressNoMLSID] BIGINT        NULL,
    [Street1MLSID]   BIGINT        NULL,
    [Street2MLSID]   BIGINT        NULL,
    [PostalCode]     NVARCHAR (20) NULL,
    [ProvinceID]     BIGINT        NULL,
    [DistrictID]     BIGINT        NULL,
    [SubdistrictID]  BIGINT        NULL,
    [TownID]         BIGINT        NULL,
    [CountryID]      BIGINT        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[GeographicRegion]...';


GO
CREATE TABLE [dbo].[GeographicRegion] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [Code]          NVARCHAR (10) NULL,
    [TitleMLSID]    BIGINT        NULL,
    [CountryID]     INT           NULL,
    [ParentID]      INT           NULL,
    [EffectiveFrom] DATETIME2 (7) NULL,
    [EffectiveTo]   DATETIME2 (7) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[GeographicRegion].[GeographicRegion_IX_CountryID]...';


GO
CREATE NONCLUSTERED INDEX [GeographicRegion_IX_CountryID]
    ON [dbo].[GeographicRegion]([CountryID] ASC, [ParentID] ASC);


GO
PRINT N'Creating [dbo].[GradingSystem]...';


GO
CREATE TABLE [dbo].[GradingSystem] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [Discriminator]   TINYINT        NULL,
    [Code]            NVARCHAR (30)  NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [TitleMLSID]      BIGINT         NULL,
    [MaxPoint]        REAL           NULL,
    [MinPoint]        REAL           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[HierarchicalCategory]...';


GO
CREATE TABLE [dbo].[HierarchicalCategory] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [Code]             NVARCHAR (30)  NULL,
    [EffectiveFrom]    DATETIME2 (7)  NULL,
    [EffectiveTo]      DATETIME2 (7)  NULL,
    [Reference]        NVARCHAR (200) NULL,
    [Remark]           NVARCHAR (400) NULL,
    [RootID]           INT            NULL,
    [ParentID]         INT            NULL,
    [DescriptionMLSID] BIGINT         NULL,
    [ShortTitleMLSID]  BIGINT         NULL,
    [TitleMLSID]       BIGINT         NULL,
    [LevelNo]          INT            NULL,
    [SeqNo]            INT            NULL,
    [Weight]           REAL           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Language]...';


GO
CREATE TABLE [dbo].[Language] (
    [LanguageCode]    NCHAR (5)       NOT NULL,
    [SeqNo]           INT             NULL,
    [ShortTitle]      NVARCHAR (20)   NULL,
    [SmallImageBytes] VARBINARY (MAX) NULL,
    [Title]           NVARCHAR (40)   NULL,
    PRIMARY KEY CLUSTERED ([LanguageCode] ASC)
);


GO
PRINT N'Creating [dbo].[MLSValue]...';


GO
CREATE TABLE [dbo].[MLSValue] (
    [ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [MLSID]        BIGINT          NULL,
    [LanguageCode] NCHAR (5)       NULL,
    [LanguageID]   INT             NULL,
    [Value]        NVARCHAR (4000) NULL,
    [UpdatedTS]    DATETIME2 (7)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[MultilingualString]...';


GO
CREATE TABLE [dbo].[MultilingualString] (
    [MLSID]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [Code]   NVARCHAR (20)  NULL,
    [Remark] NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([MLSID] ASC)
);


GO
PRINT N'Creating [dbo].[Organization]...';


GO
CREATE TABLE [dbo].[Organization] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [CurrentNameID]             INT            NULL,
    [Discriminator]             TINYINT        NULL,
    [EffectiveFrom]             DATETIME2 (7)  NULL,
    [EffectiveTo]               DATETIME2 (7)  NULL,
    [Reference]                 NVARCHAR (200) NULL,
    [Remark]                    NVARCHAR (400) NULL,
    [OfficialIDNo]              NVARCHAR (50)  NULL,
    [EmailAddress]              NVARCHAR (50)  NULL,
    [URL]                       NVARCHAR (500) NULL,
    [CategoryID]                INT            NULL,
    [SupervisoryOrganizationID] BIGINT         NULL,
    [MaxClassLevelID]           INT            NULL,
    [MinClassLevelID]           INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[OrgName]...';


GO
CREATE TABLE [dbo].[OrgName] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [OrganizationID]  INT            NULL,
    [TitleMLSID]      BIGINT         NULL,
    [ShortTitleMLSID] BIGINT         NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (50)  NULL,
    [Remark]          NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[PartyAddress]...';


GO
CREATE TABLE [dbo].[PartyAddress] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [PartyID]             INT            NOT NULL,
    [PartyDiscriminator]  TINYINT        NULL,
    [CategoryID]          BIGINT         NULL,
    [EffectiveFrom]       DATETIME       NULL,
    [EffectiveTo]         DATETIME       NULL,
    [Reference]           NVARCHAR (200) NULL,
    [Remark]              NVARCHAR (400) NULL,
    [GeographicAddressID] INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[PartyIdentity]...';


GO
CREATE TABLE [dbo].[PartyIdentity] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [PartyID]            INT            NOT NULL,
    [PartyDiscriminator] TINYINT        NULL,
    [CategoryID]         INT            NULL,
    [EffectiveFrom]      DATETIME       NULL,
    [EffectiveTo]        DATETIME       NULL,
    [Reference]          NVARCHAR (200) NULL,
    [Remark]             NVARCHAR (400) NULL,
    [IDNo]               NVARCHAR (30)  NOT NULL,
    [IssuedBy]           INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Password]...';


GO
CREATE TABLE [dbo].[Password] (
    [ID]                BIGINT         NOT NULL,
    [UserID]            INT            NULL,
    [EncryptedPassword] NVARCHAR (512) NULL,
    [EffectiveFrom]     DATETIME2 (7)  NULL,
    [EffectiveTo]       DATETIME2 (7)  NULL,
    [Reference]         NVARCHAR (50)  NULL,
    [Remark]            NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Password].[Password_IX_User]...';


GO
CREATE NONCLUSTERED INDEX [Password_IX_User]
    ON [dbo].[Password]([UserID] ASC);


GO
PRINT N'Creating [dbo].[PerformanceIndicator]...';


GO
CREATE TABLE [dbo].[PerformanceIndicator] (
    [ID]                  INT           IDENTITY (1, 1) NOT NULL,
    [DescriptionMLSID]    BIGINT        NULL,
    [ClassLevelOutcomeID] BIGINT        NULL,
    [ClassLevelID]        BIGINT        NULL,
    [EffectiveFrom]       DATETIME2 (7) NULL,
    [EffectiveTo]         DATETIME2 (7) NULL,
    [SequenceNo]          INT           NULL,
    [Weight]              REAL          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[PerformanceMeasurement]...';


GO
CREATE TABLE [dbo].[PerformanceMeasurement] (
    [ID]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [DescriptionMLSID]       BIGINT        NULL,
    [ClassLevelOutcomeID]    BIGINT        NULL,
    [ClassLevelID]           BIGINT        NULL,
    [EffectiveFrom]          DATETIME2 (7) NULL,
    [EffectiveTo]            DATETIME2 (7) NULL,
    [ClassSectionID]         INT           NULL,
    [SemesterID]             INT           NULL,
    [StudentID]              INT           NULL,
    [PerformanceIndicatorID] INT           NULL,
    [SequenceNo]             INT           NULL,
    [Point]                  REAL          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Person]...';


GO
CREATE TABLE [dbo].[Person] (
    [ID]                 INT            NOT NULL,
    [CurrentNameID]      INT            NULL,
    [BloodGroupNodeID]   INT            NULL,
    [CitizenOfCountryID] INT            NULL,
    [GenderID]           INT            NULL,
    [EmailAddress]       NVARCHAR (50)  NULL,
    [HomePhoneNo]        NVARCHAR (50)  NULL,
    [MobilePhoneNo]      NVARCHAR (50)  NULL,
    [OccupationID]       INT            NULL,
    [OfficialIDNo]       NVARCHAR (20)  NULL,
    [RaceID]             INT            NULL,
    [ReligionID]         INT            NULL,
    [BirthDate]          DATETIME2 (7)  NULL,
    [BirthCertificate]   NVARCHAR (30)  NULL,
    [DeceasedDate]       DATETIME2 (7)  NULL,
    [DeathCertificate]   NVARCHAR (30)  NULL,
    [Reference]          NVARCHAR (50)  NULL,
    [Remark]             NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[PersonName]...';


GO
CREATE TABLE [dbo].[PersonName] (
    [ID]              INT            NOT NULL,
    [PersonID]        INT            NULL,
    [PrefixMLSID]     INT            NULL,
    [FirstNameMLSID]  BIGINT         NULL,
    [MiddleNameMLSID] BIGINT         NULL,
    [LastNameMLSID]   BIGINT         NULL,
    [EffectiveFrom]   DATETIME2 (7)  NULL,
    [EffectiveTo]     DATETIME2 (7)  NULL,
    [Reference]       NVARCHAR (50)  NULL,
    [Remark]          NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Photo]...';


GO
CREATE TABLE [dbo].[Photo] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [PersonID]  INT            NULL,
    [Date]      DATETIME2 (7)  NULL,
    [Reference] NVARCHAR (200) NULL,
    [Remark]    NVARCHAR (400) NULL,
    [Image]     NTEXT          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Punishment]...';


GO
CREATE TABLE [dbo].[Punishment] (
    [ID]                     INT            IDENTITY (1, 1) NOT NULL,
    [Code]                   NVARCHAR (30)  NULL,
    [Date]                   DATETIME2 (7)  NULL,
    [Description]            NVARCHAR (400) NULL,
    [Reference]              NVARCHAR (200) NULL,
    [Remark]                 NVARCHAR (400) NULL,
    [StudentID]              INT            NULL,
    [PerformanceIndicatorID] INT            NULL,
    [DeductedPoint]          REAL           NULL,
    [WrongDoingCategoryID]   INT            NULL,
    [PunishmentCategoryID]   INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Receipt]...';


GO
CREATE TABLE [dbo].[Receipt] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [Date]         DATETIME2 (7)  NULL,
    [ReceiptNo]    NVARCHAR (50)  NULL,
    [SemesterID]   INT            NULL,
    [PayerName]    NCHAR (50)     NULL,
    [PayerAddress] NVARCHAR (100) NULL,
    [SchoolID]     INT            NULL,
    [StudentID]    INT            NULL,
    [TotalAmount]  REAL           NULL,
    [Reference]    NVARCHAR (50)  NULL,
    [Remark]       NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ReceiptItem]...';


GO
CREATE TABLE [dbo].[ReceiptItem] (
    [ID]               INT  IDENTITY (1, 1) NOT NULL,
    [Amount]           REAL NULL,
    [AmountPerUnit]    REAL NULL,
    [Units]            INT  NULL,
    [ReceiptID]        INT  NULL,
    [ReceivableItemID] INT  NULL,
    [SeqNo]            INT  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ReceiptTemplate]...';


GO
CREATE TABLE [dbo].[ReceiptTemplate] (
    [ID]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [SchoolID]    INT            NULL,
    [ReceiptNote] NVARCHAR (100) NULL,
    [TotalAmount] REAL           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ReceiptTemplateItem]...';


GO
CREATE TABLE [dbo].[ReceiptTemplateItem] (
    [ID]                   BIGINT IDENTITY (1, 1) NOT NULL,
    [SeqNo]                INT    NULL,
    [ReceiptTemplateID]    INT    NULL,
    [ReceivableItemID]     INT    NULL,
    [DefaultAmount]        REAL   NULL,
    [DefaultAmountPerUnit] REAL   NULL,
    [DefaultUnits]         INT    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[ReceivableItem]...';


GO
CREATE TABLE [dbo].[ReceivableItem] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom] DATETIME2 (7) NULL,
    [EffectiveTo]   DATETIME2 (7) NULL,
    [Reference]     NVARCHAR (50) NULL,
    [Remark]        NVARCHAR (50) NULL,
    [SeqNo]         INT           NULL,
    [SchoolID]      INT           NULL,
    [TitleMLSID]    BIGINT        NULL,
    [DefaultAmount] MONEY         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Register]...';


GO
CREATE TABLE [dbo].[Register] (
    [RegisterID]     INT           NOT NULL,
    [UserID]         INT           NOT NULL,
    [SemesterID]     INT           NOT NULL,
    [SchoolID]       INT           NOT NULL,
    [Subject_Amount] INT           NULL,
    [Create_Date]    DATETIME2 (7) NULL,
    [Update_Date]    DATETIME2 (7) NULL,
    PRIMARY KEY CLUSTERED ([RegisterID] ASC)
);


GO
PRINT N'Creating [dbo].[RegisterDetail]...';


GO
CREATE TABLE [dbo].[RegisterDetail] (
    [RegisterDetailID] INT            NOT NULL,
    [RegisterID]       INT            NOT NULL,
    [Curriculum]       INT            NOT NULL,
    [StudentID]        INT            NOT NULL,
    [TeacherID]        INT            NOT NULL,
    [Status]           NVARCHAR (50)  NULL,
    [Remark]           NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([RegisterDetailID] ASC)
);


GO
PRINT N'Creating [dbo].[RegisterPayment]...';


GO
CREATE TABLE [dbo].[RegisterPayment] (
    [RegisterPaymentID] INT             NOT NULL,
    [RegisterDetailID]  INT             NOT NULL,
    [CourseID]          INT             NOT NULL,
    [UserID]            INT             NOT NULL,
    [Price]             DECIMAL (18, 2) NULL,
    [Unit]              INT             NULL,
    [Create_Date]       DATETIME2 (7)   NULL,
    [Update_Date]       DATETIME2 (7)   NULL,
    PRIMARY KEY CLUSTERED ([RegisterPaymentID] ASC)
);


GO
PRINT N'Creating [dbo].[Reward]...';


GO
CREATE TABLE [dbo].[Reward] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (30)  NULL,
    [Date]        DATETIME2 (7)  NULL,
    [Description] NVARCHAR (400) NULL,
    [Reference]   NVARCHAR (200) NULL,
    [Remark]      NVARCHAR (400) NULL,
    [CategoryID]  INT            NULL,
    [StudentID]   INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Role]...';


GO
CREATE TABLE [dbo].[Role] (
    [ID]               INT            IDENTITY (1, 1) NOT NULL,
    [Code]             NVARCHAR (30)  NULL,
    [ApplicationID]    INT            NULL,
    [DescriptionMLSID] BIGINT         NULL,
    [ShortTitleMLSID]  BIGINT         NULL,
    [TitleMLSID]       BIGINT         NULL,
    [EffectiveFrom]    DATETIME2 (7)  NULL,
    [EffectiveTo]      DATETIME2 (7)  NULL,
    [Reference]        NVARCHAR (200) NULL,
    [Remark]           NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Room]...';


GO
CREATE TABLE [dbo].[Room] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [Code]          NVARCHAR (30)  NULL,
    [EffectiveFrom] DATETIME2 (7)  NULL,
    [EffectiveTo]   DATETIME2 (7)  NULL,
    [Reference]     NVARCHAR (200) NULL,
    [Remark]        NVARCHAR (400) NULL,
    [SchoolID]      INT            NULL,
    [BuildingTitle] NVARCHAR (200) NULL,
    [RoomNo]        NVARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[RoyalDecoration]...';


GO
CREATE TABLE [dbo].[RoyalDecoration] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [Date]                      DATETIME2 (7)  NULL,
    [Reference]                 NVARCHAR (200) NULL,
    [Remark]                    NVARCHAR (400) NULL,
    [RoyalDecorationCategoryID] INT            NULL,
    [PersonID]                  INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[SchoolAdministrator]...';


GO
CREATE TABLE [dbo].[SchoolAdministrator] (
    [ID]            INT            NOT NULL,
    [CategoryID]    INT            NULL,
    [PersonID]      INT            NULL,
    [SchoolID]      INT            NULL,
    [EffectiveFrom] DATETIME2 (7)  NULL,
    [EffectiveTo]   DATETIME2 (7)  NULL,
    [Reference]     NVARCHAR (50)  NULL,
    [Remark]        NVARCHAR (500) NULL,
    [StatusID]      INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[SchoolOutcomeCategoryGrading]...';


GO
CREATE TABLE [dbo].[SchoolOutcomeCategoryGrading] (
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [Code]              NVARCHAR (30)  NULL,
    [EffectiveFrom]     DATETIME2 (7)  NULL,
    [EffectiveTo]       DATETIME2 (7)  NULL,
    [Reference]         NVARCHAR (200) NULL,
    [Remark]            NVARCHAR (400) NULL,
    [GradingSystemID]   INT            NULL,
    [OutcomeCategoryID] INT            NULL,
    [SchoolID]          INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Semester]...';


GO
CREATE TABLE [dbo].[Semester] (
    [ID]              BIGINT        IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom]   DATETIME2 (7) NULL,
    [EffectiveTo]     DATETIME2 (7) NULL,
    [AcademicYear]    INT           NULL,
    [SemesterNo]      INT           NULL,
    [SchoolID]        INT           NULL,
    [SemesterID]      BIGINT        NULL,
    [ApplicationFrom] DATETIME2 (7) NULL,
    [ApplicationTo]   DATETIME2 (7) NULL,
    [TeachingFrom]    DATETIME2 (7) NULL,
    [TeachingTo]      DATETIME2 (7) NULL,
    [FinalExamFrom]   DATETIME2 (7) NULL,
    [FinalExamTo]     DATETIME2 (7) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Student]...';


GO
CREATE TABLE [dbo].[Student] (
    [ID]                   BIGINT         NOT NULL,
    [IDNo]                 NVARCHAR (20)  NULL,
    [CategoryID]           INT            NULL,
    [PersonID]             INT            NULL,
    [SchoolID]             INT            NULL,
    [EffectiveFrom]        DATETIME2 (7)  NULL,
    [EffectiveTo]          DATETIME2 (7)  NULL,
    [Reference]            NVARCHAR (50)  NULL,
    [Remark]               NVARCHAR (500) NULL,
    [CurriculumID]         INT            NULL,
    [StartSemesterID]      INT            NULL,
    [StatusID]             INT            NULL,
    [MajorID]              INT            NULL,
    [AdmittedClassLevelID] INT            NULL,
    [AdmittedAcademicYear] INT            NULL,
    [AdmittedSemesterID]   INT            NULL,
    [AdmittedSemesterNo]   INT            NULL,
    [AdmittedGPA]          REAL           NULL,
    [CurrentGPA]           REAL           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[StudentAcademicYear]...';


GO
CREATE TABLE [dbo].[StudentAcademicYear] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [SchoolID]        INT            NULL,
    [StudentID]       INT            NULL,
    [AcademicYear]    INT            NULL,
    [BehavioralPoint] REAL           NULL,
    [ClassLevelID]    INT            NULL,
    [DeductedPoint]   REAL           NULL,
    [GPA]             REAL           NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[StudentApplication]...';


GO
CREATE TABLE [dbo].[StudentApplication] (
    [ID]                  INT            IDENTITY (1, 1) NOT NULL,
    [Date]                DATETIME2 (7)  NULL,
    [AdmissionID]         INT            NULL,
    [AdmissionTestRoomID] INT            NULL,
    [Reference]           NVARCHAR (200) NULL,
    [Remark]              NVARCHAR (400) NULL,
    [IDNo]                NVARCHAR (20)  NULL,
    [AppliedCurriculumID] INT            NULL,
    [AppliedDate]         DATETIME2 (7)  NULL,
    [ApplicantID]         INT            NULL,
    [FatherID]            INT            NULL,
    [GuardianID]          INT            NULL,
    [MotherID]            INT            NULL,
    [StudentID]           INT            NULL,
    [LastSchoolID]        INT            NULL,
    [LastClassLevelID]    INT            NULL,
    [GPA]                 REAL           NULL,
    [ONETScore]           REAL           NULL,
    [TotalTestScore]      REAL           NULL,
    [Rank]                INT            NULL,
    [IsAdmitted]          BIT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[StudentSemester]...';


GO
CREATE TABLE [dbo].[StudentSemester] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [SchoolID]        INT            NULL,
    [StudentID]       INT            NULL,
    [SemesterID]      INT            NULL,
    [BehavioralPoint] REAL           NULL,
    [ClassLevelID]    INT            NULL,
    [DeductedPoint]   REAL           NULL,
    [GPA]             REAL           NULL,
    [Reference]       NVARCHAR (200) NULL,
    [Remark]          NVARCHAR (400) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[Teacher]...';


GO
CREATE TABLE [dbo].[Teacher] (
    [ID]                INT            NOT NULL,
    [IDNo]              NVARCHAR (20)  NULL,
    [CategoryID]        INT            NULL,
    [PersonID]          INT            NULL,
    [SchoolID]          INT            NULL,
    [EffectiveFrom]     DATETIME2 (7)  NULL,
    [EffectiveTo]       DATETIME2 (7)  NULL,
    [Reference]         NVARCHAR (50)  NULL,
    [Remark]            NVARCHAR (500) NULL,
    [StartAcademicYear] INT            NULL,
    [StartSemesterID]   INT            NULL,
    [StartSemesterNo]   INT            NULL,
    [StatusID]          INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[TestScore]...';


GO
CREATE TABLE [dbo].[TestScore] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [AdmissionTestID]      INT            NULL,
    [Remark]               NVARCHAR (400) NULL,
    [StudentApplicationID] INT            NULL,
    [Score]                REAL           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [ID]                          BIGINT         NOT NULL,
    [ApplicationID]               INT            NULL,
    [LoginName]                   NVARCHAR (50)  NULL,
    [PersonID]                    BIGINT         NULL,
    [OrganizationID]              INT            NULL,
    [IsDisable]                   BIT            NULL,
    [LastLoginTimestamp]          DATETIME2 (7)  NULL,
    [LastFailedLoginTimestamp]    DATETIME2 (7)  NULL,
    [ConsecutiveFailedLoginCount] INT            NULL,
    [CurrentPasswordID]           BIGINT         NULL,
    [BirthDate]                   DATETIME2 (7)  NULL,
    [DeceasedDate]                DATETIME2 (7)  NULL,
    [EffectiveFrom]               DATETIME2 (7)  NULL,
    [EffectiveTo]                 DATETIME2 (7)  NULL,
    [Reference]                   NVARCHAR (50)  NULL,
    [Remark]                      NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[UserRole]...';


GO
CREATE TABLE [dbo].[UserRole] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [EffectiveFrom] DATETIME2 (7)  NULL,
    [EffectiveTo]   DATETIME2 (7)  NULL,
    [Reference]     NVARCHAR (200) NULL,
    [Remark]        NVARCHAR (400) NULL,
    [UserID]        INT            NULL,
    [RoleID]        INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '58052ab5-7c11-407e-bb3e-7de711e41fad')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('58052ab5-7c11-407e-bb3e-7de711e41fad')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '67c7f9bb-b5d4-4b2f-bee9-8d5a5cc432ec')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('67c7f9bb-b5d4-4b2f-bee9-8d5a5cc432ec')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3d3db7e3-e097-4d1e-941d-b3f0fcb88a2e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3d3db7e3-e097-4d1e-941d-b3f0fcb88a2e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'a594cac8-1fa1-4674-9457-0576692dc713')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('a594cac8-1fa1-4674-9457-0576692dc713')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'd10be975-513c-4329-a603-a0f99b8bc63f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('d10be975-513c-4329-a603-a0f99b8bc63f')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'de0d6c88-09cb-405a-b72b-a166dfb77ee9')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('de0d6c88-09cb-405a-b72b-a166dfb77ee9')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '91512ec2-4636-4670-8645-8c617302b1c5')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('91512ec2-4636-4670-8645-8c617302b1c5')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '43b44248-25da-4941-adc3-1262624a7838')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('43b44248-25da-4941-adc3-1262624a7838')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c59e8f40-4c68-492e-b6fa-179346efee17')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c59e8f40-4c68-492e-b6fa-179346efee17')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '19487e5b-1320-438d-bfea-e082abf063b7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('19487e5b-1320-438d-bfea-e082abf063b7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '8656c0f3-b7d3-4a59-835a-63fb56333ec5')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('8656c0f3-b7d3-4a59-835a-63fb56333ec5')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1cb7f502-6c7e-4320-947e-b971d60c0e7b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1cb7f502-6c7e-4320-947e-b971d60c0e7b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5cd091f4-d593-40fc-92bc-a0cf3eba940a')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5cd091f4-d593-40fc-92bc-a0cf3eba940a')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1872c8cc-dc3d-4fb8-9586-b663c2119000')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1872c8cc-dc3d-4fb8-9586-b663c2119000')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0e87e826-e136-4faf-812b-003b0a943b5e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0e87e826-e136-4faf-812b-003b0a943b5e')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'df20f48b-25ca-4c4a-8f13-2ef7352deb8d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('df20f48b-25ca-4c4a-8f13-2ef7352deb8d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5e482b0f-192d-41fb-beca-7e7ef613091b')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5e482b0f-192d-41fb-beca-7e7ef613091b')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f4e2e437-f021-4327-a5df-0cc523403af9')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f4e2e437-f021-4327-a5df-0cc523403af9')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6c92e556-8130-4ce0-b9db-96a6ec385eb3')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6c92e556-8130-4ce0-b9db-96a6ec385eb3')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '44c22e2e-791e-4091-8b78-e624c28cfd7f')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('44c22e2e-791e-4091-8b78-e624c28cfd7f')

GO

GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Update complete.';


GO
